### ISSUE TITLE
question about GAP in model GF

### ISSUE THREAD

**Issue by rechawine** [nii-yamagishilab/project-NN-Pytorch-scripts#26]
`
# just a place holder
            self.m_transform.append(
                torch_nn.Sequential(
                    torch_nn.Identity()
                )
            )

            self.m_before_pooling.append(
                torch_nn.Sequential(
                    torch_nn.Identity()
                )
            )

            if self.v_emd_dim is None:
                self.v_emd_dim = v_feat_dim
            else:
                assert self.v_emd_dim == v_feat_dim, "v_emd_dim error"

            self.m_output_act.append(
                torch_nn.Linear(v_feat_dim, self.v_out_class)
            )
            
            self.m_frontend.append(
                torch_nn.Linear(g_ssl_model.out_dim, v_feat_dim)
            )
`
hello，in your article"nvestigating self-supervised front ends for speech spoofing countermeasures"，it write that there is a Globel Average pool module in your model GF/LGF/LLGF，but i have not see how to relase "GAP"
can you please tell me what should I do if I want to build the "GAP" module?  thanks

**Comment by TonyWangX** [comment]
Hello, sorry for the late reply. 

That operation is not a defined module, but a simple inline operation -- taking the mean over time.

For example, here:
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/58ac48a468df2f9f15ce485ab3b4087b23fd67d2/project/07-asvspoof-ssl/model-LFCC-LLGF/model.py#L380

Hope it helps!
