### ISSUE TITLE
the pretrained model of 07project(SSL) is not provided

### ISSUE THREAD

**Issue by TingziGITHUB** [nii-yamagishilab/project-NN-Pytorch-scripts#52]
hello, can you provided the pretrained model of 07project(SSL_model_W2V-XLSR-fix-LLGF)? the SSL_pretrained folder is empty.Thank you.

**Comment by TonyWangX** [comment]
Hi, sorry for the trouble.

Could you let me know whether you have executed the 00_demo.sh script following README.md?

The script will automatically download the pre-trained models from external websites.  
The pre-trained models are not saved in the Github repository. 

Specifically, the script 00_demo.sh will do the following step two steps if pre-trained models have not been downloaded:

1. download pre-trained CM models from zenodo.org 
See https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/196adad25f148dcb32bea0f487aed6ee3a28e40e/project/07-asvspoof-ssl/00_demo.sh#L36

2. call 01_download_ssl.sh to download the original SSL model from fairseq.
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/196adad25f148dcb32bea0f487aed6ee3a28e40e/project/07-asvspoof-ssl/00_demo.sh#L100

Regards,
