### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by Sir1usss** [nii-yamagishilab/project-NN-Pytorch-scripts#55]
Installed: Anaconda(python3.8)
When I run the project-07 and the env-fs-install.sh will auto install pytorch-2.1.0, but it can't be used in running project07 which require pytorch-1.8.0. Is it the wrong head of fairseq from github, which will require the version 2.1.0 of pytorch?
![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/16861124/fed11c95-9b2e-46dc-a5a7-976bd3229750)

**Comment by TonyWangX** [comment]
Sorry for the trouble.

I missed the fact that fairseq does not specify torch version in its setup.py. Therefore, pip will install the latest torch when executing `pip install --editable ./` in fairseq.

Could you try this modified env-fs-install.sh ?
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/newfunctions/env-fs-install.sh

There. torch < 2.0 will be installed before setting up fairseq. This is sufficient for the scripts and code. 
Let me know if it works. (at least it works on my side).

**Comment by Sir1usss** [comment]
Thank you for you reply.

I reinstall anconda3 and the env-fs-install.sh script, and now the fairseq-pip2 env has pytorch=1.9.0:
![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/16861124/9e14316a-0bc8-4463-959c-f7f2a50cf81f)

But meet fairseq version issue(log_eval_trained_toy_eval_set_err):
![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/16861124/ad93f551-686b-4c7d-8895-5eb88f9c7faa)

**Comment by TonyWangX** [comment]
I think the installed fairseq version is correct. Could you check

```
$: conda activate fairseq-pip2

(fairseq-pip2) $: python -c "import fairseq; print(fairseq.__version__)"
1.0.0a0+862efab

(fairseq-pip2) $: python -c "import fairseq; print(fairseq.__file__)"
pytorch-project-2020/fairseq/fairseq/__init__.py

(fairseq-pip2) $: python -c "import fairseq; import fairseq.checkpoint_utils;print(fairseq.checkpoint_utils.__file__)"
pytorch-project-2020/fairseq/fairseq/checkpoint_utils.py
```

Does your environment show something similar?  It should be able to load checkpoint_utils in fairseq.

**Comment by Sir1usss** [comment]
I have the same output:

![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/16861124/fdf5ea3f-3ed5-4a8c-95cf-92ff56ee439d)

When I use the quick start command, 
```
bash 00_demo.sh model-W2V-XLSR-ft-GF config_train_toyset 01
```
The output:

![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/16861124/78eb1e67-7238-41ed-90db-16906dcab9b4)

![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/16861124/d0bad7b4-be15-403f-99ff-04e377d10dc9)

**Comment by TonyWangX** [comment]
May you try to run the command like this?
This will manually start the training process in the model folder.
 
```bash
$ conda activate fairseq-pip2
(fairseq-pip2)$: cd model-W2V-XLSR-ft-GF/config_train_toyset/01 
(fairseq-pip2)$: python main.py --model-forward-with
-file-name --num-workers 8 --epochs 100 --no-best-epochs 10 --batch-size 8 --sampler block_shuffle_by_leng
th --lr-decay-factor 0.5 --lr-scheduler-type 1 --lr 0.000001 --not-save-each-epoch --seed 01 --module-conf
ig config_train_toyset 


-------------------------------------------------                                                         
---  Start program 2023-10-15 14:24:22.637296 ---                                                         
-------------------------------------------------                                                         
Load module: config_train_toyset                                                                          
Load module: model                                                                                        
2023-10-15 14:24:23 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tenso
rboardX                                                                                                   
---------------------------------------------------------------------------                               
---  Loading dataset asvspoof2019_toyset_trn 2023-10-15 14:24:23.617452 ---                               
---------------------------------------------------------------------------                               
Skip scanning directories                                                                                 
Read sequence info: ./asvspoof2019_toyset_trn_utt_length.dic                                              
---------------------------------------------------------------------------                               
---  Loading dataset asvspoof2019_toyset_val 2023-10-15 14:24:23.619423 ---                               
---------------------------------------------------------------------------                               
Skip scanning directories                                                                                 
Read sequence info: ./asvspoof2019_toyset_val_utt_length.dic                                              
--------------------------------------------------------                                                  
---  Start model training 2023-10-15 14:24:31.994543 ---                                                  
-------------------------------------------------------- 
```

If there is still an error,  use `python -m pdb` and the debugging mode. 
Stop at line 44 of model.py, you can check whether fairseq.checkpoint_utils is available.
```python
(fairseq-pip2)$: python -m pdb main.py --model-forward-with-file-name --num-workers 8 --epochs 100 --no-best-epochs 10 --batch-size 8 --sampler block_shuffle_by_length --lr-decay-factor 0.5 --lr-scheduler-type 1 --lr 0.000001 --not-save-each-epoch --seed 01 --module-config config_train_toyset

-> """
(Pdb) b model.py:44
(Pdb) c
-------------------------------------------------
---  Start program 2023-10-15 14:27:13.006081 ---
-------------------------------------------------
Load module: config_train_toyset
Load module: model
2023-10-15 14:27:14 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
---------------------------------------------------------------------------
---  Loading dataset asvspoof2019_toyset_trn 2023-10-15 14:27:15.353425 ---
---------------------------------------------------------------------------
Skip scanning directories
Read sequence info: ./asvspoof2019_toyset_trn_utt_length.dic
---------------------------------------------------------------------------
---  Loading dataset asvspoof2019_toyset_val 2023-10-15 14:27:15.358449 ---
---------------------------------------------------------------------------
Skip scanning directories
Read sequence info: ./asvspoof2019_toyset_val_utt_length.dic

-> model, _, _ = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
(Pdb) fairseq.checkpoint_utils.__file__
'env/fairseq/fairseq/checkpoint_utils.py'
(Pdb) fairseq.__file__
'env/fairseq/fairseq/__init__.py'
(Pdb) fairseq.__version__
'1.0.0a0+862efab'
```

**Comment by Sir1usss** [comment]
To solve  "AttributeError: module 'fairseg' has no attribute 'checkpoint utils' " problem, I have added these code into model-W2V-XLSR-ft-GF/config_train_toyset/01/main.py,
```
import sys
sys.path.append('/home/sirius/Documents/project-NN-Pytorch-scripts-2/fairseq')
```

log_eval_trained_toy_eval_set_err and log_train_err are no content at all.

But the train.py will finished, could you tell me the memory and graphics requirements for training? Maybe the memory overflow.

**Comment by TonyWangX** [comment]
When installing fairseq by `pip install --editable ./` in env-fs-install.sh, package should be automatically added to the python path. 

In fact, it should be available in `site-packages` of your conda environment
```bash
$: conda activate fairseq-pip2
(fairseq-pip2) $: python -c "import sys;print([x for x in sys.path if x.endswith('site-packages')][0])" | xargs -I{} ls {} | grep fairseq
__editable___fairseq_1_0_0a0_862efab_finder.py
__editable__.fairseq-1.0.0a0+862efab.pth
fairseq-1.0.0a0+862efab.dist-info
```  
In my case, the py file above will have the code that points to the actual location of the fairseq. 

If you can import fairseq but not the expected version with checkpoint_utils, I guess there are multiple versions of fairseq in that conda environment?  

Anyway, it is good to know that it is solved somehow :) Sorry for the trouble at the very beginning!



I can use tesla_p100 with 16G mem for training in the demo script. 
If GPU mem overflows, log_train_err should show something like
```
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 15.90 GiB total capacity; 14.73 GiB already allocated; 25.75 MiB free; 14.91 GiB reserved in total by PyTorch)
```

Could you also check log_train and log_eval_pretrained_toy_eval_set?
If nothing is written in the log,  the printed messages from stdout may have not been redirected to the log file by the Ubuntu OS.  In that case, after the job quits, messages should be printed to the log.

**Comment by Sir1usss** [comment]
Thank you for your patient response. I think I have solved my problem because the CPU I assigned to him only has 2 cores and 4g mem, os kill the trainning process I think. ^ ^.

**Comment by TonyWangX** [comment]
Thanks for the feedback!
I update the script in the main here
#56
