### ISSUE TITLE
About 07-asvspoof -ssl

### ISSUE THREAD

**Issue by playeraaaa** [nii-yamagishilab/project-NN-Pytorch-scripts#57]
When I reproduce the experiment using model-w2v-XLSR-fix-LLGF, there is no problem, but when changing the model to model-w2v-Small-fix-LLGF, the following error is reported, can you please look at what could be the problem?

![QQ图片20231112222808](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/46911034/8220bd47-c96d-4a22-b3c7-dcba676ab8e3)

**Comment by TonyWangX** [comment]
@playeraaaa sorry for the inconvenience. 

It seems to an error when loading the SSL model using fairseq. 
On my side, I don't see this issue.

Could  you
1. check the md5sum of the SSL model?
```bash
# Go to folder 07-asvspoof-ssl.
# The SSL model should have been downloaded to 07-asvspoof-ssl/SSL_pretrained after running the script.
# Then check
$: md5sum SSL_pretrained/wav2vec_small.pt 
238cb6ab5a85ead0be9f85c35e330e9d  SSL_pretrained/wav2vec_small.pt
```

2. check the fairseq version
```bash
$: python -c "import fairseq;print(fairseq.__version__)"
1.0.0a0+862efab
```

Meanwhile, could you copy and paste the error message? 
I cannot see the full Python debug information from the screenshot.

**Comment by playeraaaa** [comment]
Thank you very much for writing back.I checked the two messages you mentioned.
After comparing the first  hash agrees with the one you gave. But the second fairseq version is shown below:
![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/46911034/d54d27b0-77d8-49f0-aed3-c57d1ad838c4)
Could it be because of the version of fairseq? Or I try to download the ssl model again using the command?
Also attached here is the full error message.
![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/46911034/e5449671-9a7a-4dbd-a9aa-5b54bd0606ad)
Thanks again for your answer!

**Comment by TonyWangX** [comment]
If the md5sum value is the same, I guess the reason may be the fairseq version. 

Could you followed  https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/master/env-fs-install.sh and install fairseq?

**Comment by playeraaaa** [comment]
Hello, when I was configuring the environment before, I didn't follow the steps in the file because the CUDA version of the laboratory server was only 10.1 and cannot be changed. Today, I tried again, but unfortunately, the version is not compatible. The error message is as follows:
![image](https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/assets/46911034/2ffe9400-dc70-4cd7-b71e-ae7158f98f61)
May I ask if the version of fairseq can be appropriately reduced?

**Comment by TonyWangX** [comment]
Sorry for the delayed reply. It was a very busy December. 

You may try to install different versions of fairseq. I am not sure how it works. I used to have errors when I used use a different version of fairseq. They changed the data structure time to time. 

> CUDA version of the laboratory server was only 10.1 
I think as long as the Nvidia driver version is high enough, you don't need the Nvidia CUDA package installed on the system. 

```sh
$: nvidia-smi | grep Driver
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
```
Here, my Nvidia driver 460.32.03 can support up to CUDA 11.8, even though the native CUDA is 11.2
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id3


So, I can install and use cudatoolkit 11.3 by
```# CUDA 11.3
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
```
https://pytorch.org/get-started/previous-versions/


You may have a try!
