### ISSUE TITLE
Potential performance issue: concat slow in pandas below 1.4.4 version

### ISSUE THREAD

**Issue by TendouArisu** [nii-yamagishilab/project-NN-Pytorch-scripts#59]
**Issue Description:**

Hello.
I have discovered a performance degradation in the `.concat` function of pandas version 1.4.3. And I notice the repository depends on pandas 1.4.3 in `env-fs-install.sh`.  I am not sure whether this performance problem in pandas will affect this repository. I found some discussions on pandas GitHub related to this issue, including [#47501](https://github.com/pandas-dev/pandas/issues/47501) and [#47508](https://github.com/pandas-dev/pandas/pull/47508).
I also found that `sandbox/eval_asvspoof_wrapper.py` and `project/06-asvspoof-ood/02_metrics.ipynb` used the influenced api. There may be more files using the influenced api.

**Suggestion**

I would recommend considering an upgrade to a different version of pandas >= 1.4.4 or exploring other solutions to optimize the performance of `.concat`.
Any other workarounds or solutions would be greatly appreciated.
Thank you!

**Comment by TonyWangX** [comment]
Hi @TendouArisu 
Thank you very much!

I mainly use pandas concat for off-line evaluation (or for the tutorial notebook in 02_metrics.ipynb). Hence, I am not familiar with the issue and optimization of pandas. 

> I would recommend considering an upgrade to a different version of pandas >= 1.4.4 or exploring other solutions to optimize the performance of .concat.

Let me know how to optimize. Highly appreciated!
